const PizzaList = [
  {
    id: 1,
    name: "Margherita",
    ingredients: "Tomato Sauce, Mozzarella, Basil, Olive Oil",
    availableQuantity: 0,
    image: "images/margherita.jpg",
  },
  {
    id: 2,
    name: "Pepperoni",
    ingredients: "Tomato Sauce, Mozzarella, Pepperoni",
    availableQuantity: 10,
    image: "images/Pepperoni.png",
  },
  {
    id: 3,
    name: "Hawaiian",
    ingredients: "Tomato Sauce, Mozzarella, Ham, Pineapple",
    availableQuantity: 8,
    image: "images/Hawaiian.jpg",
  },
  {
    id: 4,
    name: "BBQ Chicken",
    ingredients: "BBQ Sauce, Chicken, Red Onion, Mozzarella",
    availableQuantity: 0,
    image: "images/BBQ Chicken.jpg",
  },
  {
    id: 5,
    name: "Veggie Delight",
    ingredients:
      "Tomato Sauce, Mozzarella, Bell Peppers, Onion, Mushrooms, Olives",
    availableQuantity: 20,
    image: "images/Veggie Delight.jpg",
  },
  {
    id: 6,
    name: "Meat Lovers",
    ingredients: "Tomato Sauce, Mozzarella, Pepperoni, Sausage, Bacon, Ham",
    availableQuantity: 0,
    image: "images/Meat Lovers.jpg",
  },
  {
    id: 7,
    name: "Four Cheese",
    ingredients: "Tomato Sauce, Mozzarella, Parmesan, Cheddar, Gorgonzola",
    availableQuantity: 9,
    image: "images/Four Cheese.jpeg",
  },
  {
    id: 8,
    name: "Buffalo Chicken",
    ingredients: "Buffalo Sauce, Chicken, Red Onion, Mozzarella, Blue Cheese",
    availableQuantity: 7,
    image: "images/Buffalo Chicken.jpeg",
  },
  {
    id: 9,
    name: "Supreme",
    ingredients:
      "Tomato Sauce, Mozzarella, Pepperoni, Onion, Bell Peppers, Mushrooms, Olives",
    availableQuantity: 11,
    image: "images/Supreme.jpeg",
  },
  {
    id: 10,
    name: "Spinach Alfredo",
    ingredients: "Alfredo Sauce, Spinach, Mozzarella, Garlic",
    availableQuantity: 14,
    image: "images/Spinach Alfredo.jpg",
  },
  {
    id: 11,
    name: "Mushroom & Onion",
    ingredients: "Tomato Sauce, Mozzarella, Mushrooms, Onions",
    availableQuantity: 13,
    image: "images/Mushroom & Onion.jpeg",
  },
  {
    id: 12,
    name: "Taco Pizza",
    ingredients: "Salsa, Ground Beef, Cheddar, Lettuce, Tomatoes, Olives",
    availableQuantity: 0,
    image: "images/Taco Pizza.jpg",
  },
  {
    id: 13,
    name: "Chicken Pesto",
    ingredients: "Pesto Sauce, Chicken, Mozzarella, Sun-dried Tomatoes",
    availableQuantity: 10,
    image: "images/Chicken Pesto.jpg",
  },
  {
    id: 14,
    name: "Greek Pizza",
    ingredients: "Olive Oil, Feta, Olives, Tomatoes, Spinach, Red Onions",
    availableQuantity: 12,
    image: "images/Greek Pizza.jpeg",
  },
  {
    id: 15,
    name: "Truffle Mushroom",
    ingredients: "Truffle Oil, Mushrooms, Mozzarella, Parmesan",
    availableQuantity: 0,
    image: "images/Truffle Mushroom.jpg",
  },
  {
    id: 16,
    name: "Sausage & Peppers",
    ingredients: "Tomato Sauce, Sausage, Bell Peppers, Mozzarella",
    availableQuantity: 9,
    image: "images/Sausage & Peppers.jpeg",
  },
  {
    id: 17,
    name: "Zaatar Pizza",
    ingredients: "Zaatar Spice, Olive Oil, Mozzarella",
    availableQuantity: 18,
    image: "images/Zaatar Pizza.jpeg",
  },
  {
    id: 18,
    name: "Seafood Pizza",
    ingredients: "White Sauce, Shrimp, Calamari, Mozzarella, Garlic",
    availableQuantity: 3,
    image: "images/Seafood Pizza.jpeg",
  },
  {
    id: 19,
    name: "Cheeseburger Pizza",
    ingredients: "Ketchup, Ground Beef, Pickles, Cheddar, Onions",
    availableQuantity: 0,
    image: "images/Cheeseburger Pizza.jpeg",
  },
  {
    id: 20,
    name: "Paneer Tikka",
    ingredients: "Tomato Sauce, Paneer, Onions, Bell Peppers, Spices",
    availableQuantity: 17,
    image: "images/Paneer Tikka.jpeg",
  },
];

export default PizzaList;
